//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marathon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checkpoint
    {
        public int CheckpointId { get; set; }
        public string Landmark { get; set; }
        public short Drinks { get; set; }
        public short EnergyBars { get; set; }
        public short Toilets { get; set; }
        public short Information { get; set; }
        public short Medical { get; set; }
    }
}
